runners:
  - name: "aws-runner"
    cloud: "aws"
    instance_type: "t2.nano"
    machine_image: "ami-06fd8a495a537da8b"
    preemptible: "true"
    workflow: .github/workflows/aws.yml
    labels:
      - "cirun-aws-runner"