name: AWS

on: [push]

jobs:
  build:

    runs-on: [self-hosted, cirun-aws-runner]
    steps:
    - uses: actions/checkout@v3

    - name: Get Hostname
      run: |
        hostname
    - name: Get system Information
      run: |
        uname -a
    - name: Get Memory
      run: |
        free -m
    - name: Get Architecture
      run: |
        dpkg --print-architecture